### ISSUE TITLE
Failure executing fact script

### ISSUE THREAD

**Issue by blacknell** [stefangweichinger/ansible-rclone#170]
After installing rclone via this galaxy role I'm getting fact gathering errors on all playbooks.

```log
[WARNING]: Failure executing fact script (/etc/ansible/facts.d/rclone.fact), rc: 1, err: Traceback (most recent call last):   File "/etc/ansible/facts.d/rclone.fact", line 25, in <module>     output['installed_version'] = subprocess.check_output(                                   ^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/subprocess.py", line 466, in check_output     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/usr/lib/python3.11/subprocess.py", line 548, in run     with Popen(*popenargs, **kwargs) as
process:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__     self._execute_child(args, executable, preexec_fn, close_fds,   File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child     raise child_exception_type(errno_num, err_msg,
err_filename) OSError: [Errno 8] Exec format error: 'rclone'
```

I installed the role using
```yaml
    - name: install rclone
      include_role:
        name: stefangweichinger.ansible_rclone
      when: install_rclone | default(false)
```

**Comment by stefangweichinger** [comment]
Thanks for reporting, sorry to hear. I don't know if I can help here ...
I'd try removing that fact-file and re-run etc
Any ansible-updates recently? Were you able to debug it already?

Also interesting: versions of OS, ansible ...

**Comment by stefangweichinger** [comment]
A bit googling points in the direction of wrong permissions somewhere ...

**Comment by blacknell** [comment]
It installed recline but on my RPi it was wrong arch. I deleted the facts file and moved on manually. 

Might be an idea to run the script to install rather than copy binaries.
